version: '3.8'

services:
  backend:
    build:
      context: ./burncup-be
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - postgres

  frontend:
    build:
      context: ./burncup-fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV: production
      - AUTH_SECRET: x+moMx7qVg46NDBVCsxguFtF+Oja6uy7NdFNOlV+Z7M=
      - AUTH_URL: https://burncuptesting.notchgnas.com
      - AUTH_GOOGLE_ID: 341997010337-30n42jk0qfafti3pdctciph6ftedjc4b.apps.googleusercontent.com
      - AUTH_GOOGLE_SECRET: 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
      - AUTH_TRUST_HOST: true

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: burncup_prod
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: