services:
  backend:
    build:
      context: ./burncup-be
      dockerfile: Dockerfile.dev
    volumes:
      - ./burncup-be:/app
    ports:
      - "8080:8080"
    command: ["air"]
    env_file:
      - ./burncup-be/.env.local
    depends_on:
      - frontend
      - postgres   # Add postgres as a dependency

  frontend:
    build:
      context: ./burncup-fe
      dockerfile: Dockerfile.dev
    volumes:
      - ./burncup-fe:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./burncup-fe/.env.local
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - BACKEND_INTERNAL_URL=http://backend:8080
    labels:
      - "com.microsoft.devcontainer.name=frontend"

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: burncup_dev
    ports:
      - "5432:5432"
    volumes:
      - ./burncup-be/TABLES.sql:/docker-entrypoint-initdb.d/01-tables.sql:ro
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: