-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

INSERT INTO competitions (
  id, name, description, category, image_url,
  registration_start_date, registration_end_date,
  competition_start_date, competition_end_date,
  competition_type, venue, registration_fee,
  max_members, min_members
) VALUES
  (gen_random_uuid(), 'Basketball', 'Kompetisi Basketball 3x3 dengan sistem knockout.',
   'Sports', 'https://placehold.co/600x400/FF5733/FFFFFF?text=Basketball',
   '2025-07-01', '2025-07-20', '2025-07-25', '2025-07-27',
   'Mixed', 'Lapangan Basket Binus@Bekasi', 0, 4, 3),
  (gen_random_uuid(), 'Futsal', 'Kompetisi Futsal Putra dengan sistem knockout.',
   'Sports', 'https://placehold.co/600x400/33FF57/FFFFFF?text=Futsal',
   '2025-07-01', '2025-07-20', '2025-07-25', '2025-07-27',
   'Binusian', 'Lapangan Futsal Binus@Bekasi', 0, 12, 3), -- Max players 5 + 7 subs = 12
  (gen_random_uuid(), 'Badminton', 'Kompetisi Badminton kategori Tunggal & Ganda dengan sistem knockout.',
   'Sports', 'https://placehold.co/600x400/3357FF/FFFFFF?text=Badminton',
   '2025-07-01', '2025-07-20', '2025-07-25', '2025-07-27',
   'Mixed', 'GOR Betos', 0, 2, 1), -- Max 2 for doubles, Min 1 for singles
  (gen_random_uuid(), 'Ping Pong 1v1', 'Kompetisi Ping Pong 1v1 dengan sistem knockout.',
   'Sports', 'https://placehold.co/600x400/FF33A1/FFFFFF?text=Ping+Pong',
   '2025-07-01', '2025-07-20', '2025-07-25', '2025-07-27',
   'Binusian', 'Depan Student Lounge Binus@Bekasi', 0, 1, 1),
  (gen_random_uuid(), 'Billiard 9 Ball', 'Kompetisi Billiard 9 Ball dengan sistem knockout.',
   'Sports', 'https://placehold.co/600x400/A133FF/FFFFFF?text=Billiard',
   '2025-07-01', '2025-07-20', '2025-07-25', '2025-07-27',
   'Binusian', 'Meja Billiard Lt.1 Binus@Bekasi', 0, 1, 1),
  (gen_random_uuid(), 'Volleyball', 'Kompetisi Volleyball dengan sistem knockout.',
   'Sports', 'https://placehold.co/600x400/33FFF5/FFFFFF?text=Volleyball',
   '2025-07-01', '2025-07-20', '2025-07-25', '2025-07-27',
   'Mixed', 'Lapangan Binus@Bekasi', 0, 10, 4), -- Max 10 (6 core + 4 subs), Min 4
  (gen_random_uuid(), 'Chess 1v1', 'Kompetisi Chess 1v1 dengan format Rapid Chess.',
   'Sports', 'https://placehold.co/600x400/FF8C33/FFFFFF?text=Chess',
   '2025-07-01', '2025-07-20', '2025-07-25', '2025-07-27',
   'Binusian', 'Binus Bekasi [Lantai 2 depan LSC]', 0, 1, 1),
  (gen_random_uuid(), 'Mobile Legends', 'Kompetisi Mobile Legends dengan sistem eliminasi langsung.',
   'E-Sports', 'https://placehold.co/600x400/8C33FF/FFFFFF?text=Mobile+Legends',
   '2025-07-01', '2025-07-20', '2025-07-25', '2025-07-27',
   'Mixed', 'Binus Bekasi [MMG Binus Bekasi]', 0, 6, 5), -- 5 players + 1 reserve
  (gen_random_uuid(), 'Valorant', 'Kompetisi Valorant dengan sistem eliminasi langsung.',
   'E-Sports', 'https://placehold.co/600x400/33FF8C/FFFFFF?text=Valorant',
   '2025-07-01', '2025-07-20', '2025-07-25', '2025-07-27',
   'Mixed', 'Remote [Dilakukan di rumah masing-masing namun harus on camera]', 0, 5, 5),
  (gen_random_uuid(), 'FIFA 1v1', 'Kompetisi FIFA 1v1 dengan sistem knockout.',
   'E-Sports', 'https://placehold.co/600x400/FF3333/FFFFFF?text=FIFA',
   '2025-07-01', '2025-07-20', '2025-07-25', '2025-07-27',
   'Mixed', 'Binus Bekasi [Fun Corner, MMG Binus Bekasi]', 0, 1, 1),
  (gen_random_uuid(), 'PUBG Mobile', 'Kompetisi PUBG Mobile dengan sistem scoring sheet.',
   'E-Sports', 'https://placehold.co/600x400/33A1FF/FFFFFF?text=PUBG+Mobile',
   '2025-07-01', '2025-07-20', '2025-07-25', '2025-07-25', -- Assuming 2-day competition ends on the 26th
   'Mixed', 'R412 Binus@Bekasi', 0, 4, 1),
  (gen_random_uuid(), 'Block Blast', 'Kompetisi Block Blast berdasarkan skor tertinggi.',
   'E-Sports', 'https://placehold.co/600x400/A1FF33/FFFFFF?text=Block+Blast',
   '2025-07-01', '2025-07-20', '2025-07-25', '2025-07-27',
   'Mixed', 'Binus Bekasi (R4013)', 0, 1, 1),
  (gen_random_uuid(), 'Modern Dance', 'Kompetisi Modern Dance dengan tema Latin EDM dan Pop.',
   'Creative', 'https://placehold.co/600x400/FF33F5/FFFFFF?text=Modern+Dance',
   '2025-07-01', '2025-07-20', '2025-07-25', '2025-07-27',
   'Mixed', 'Binus Bekasi [Lapangan Basket]', 0, 6, 4),
  (gen_random_uuid(), 'Ratoh Jaroe', 'Kompetisi Tari Ratoh Jaroe.',
   'Creative', 'https://placehold.co/600x400/33FFD5/FFFFFF?text=Ratoh+Jaroe',
   '2025-07-01', '2025-07-20', '2025-07-25', '2025-07-27',
   'NonBinusian', 'Binus Bekasi MMG', 0, 20, 12),
  (gen_random_uuid(), 'Band', 'Kompetisi Band dengan genre Rock Alternatif dan Pop Kreatif.',
   'Creative', 'https://placehold.co/600x400/F5FF33/FFFFFF?text=Band',
   '2025-07-01', '2025-07-20', '2025-07-25', '2025-07-27',
   'Binusian', 'Binus Bekasi [MMG Lobby]', 0, 7, 3),
  (gen_random_uuid(), 'Cosplay', 'Kompetisi Cosplay karakter Anime/Manga dan Game.',
   'Creative', 'https://placehold.co/600x400/FF338C/FFFFFF?text=Cosplay',
   '2025-07-01', '2025-07-20', '2025-07-25', '2025-07-27',
   'Binusian', 'Lapangan Basket Binus @Bekasi', 0, 3, 1),
  (gen_random_uuid(), 'Art (Sketching)', 'Lomba menggambar langsung dari model hidup (live model drawing).',
   'Creative', 'https://placehold.co/600x400/338CFF/FFFFFF?text=Art+Sketching',
   '2025-07-01', '2025-07-20', '2025-07-25', '2025-07-27',
   'Binusian', 'Binus Bekasi [Lobby MMG]', 0, 1, 1),
  (gen_random_uuid(), 'Cake Decoration', 'Lomba dekorasi kue dengan tema Fairy Tale.',
   'Creative', 'https://placehold.co/600x400/8CFF33/FFFFFF?text=Cake+Decoration',
   '2025-07-01', '2025-07-20', '2025-07-25', '2025-07-27',
   'Mixed', 'Binus Bekasi [Kantin]', 0, 3, 2),
  (gen_random_uuid(), 'The Ultimate Automotive Show', 'Kompetisi pameran otomotif untuk mobil dan motor.',
   'Automotive', 'https://placehold.co/600x400/F533FF/FFFFFF?text=Automotive+Show',
   '2025-07-01', '2025-07-20', '2025-07-25', '2025-07-27',
   'Binusian', 'Binus Bekasi (di depan halte bus Binus Bekasi)', 0, 1, 1)
ON CONFLICT (name) DO NOTHING;

-- Insert Prizes for each competition
INSERT INTO prizes (id, competition_id, name, description)
SELECT gen_random_uuid(), c.id, p.name, p.description
FROM (VALUES
  ('Basketball', 'Juara 1', 'Hadiah Menarik + Sertifikat'),
  ('Basketball', 'Juara 2', 'Hadiah Menarik + Sertifikat'),
  ('Futsal', 'Juara 1', 'Hadiah Menarik + Sertifikat'),
  ('Futsal', 'Juara 2', 'Hadiah Menarik + Sertifikat'),
  ('Badminton', 'Juara 1', 'Hadiah Menarik + Sertifikat'),
  ('Badminton', 'Juara 2', 'Hadiah Menarik + Sertifikat'),
  ('Ping Pong 1v1', 'Juara 1', 'Hadiah Menarik + Sertifikat'),
  ('Ping Pong 1v1', 'Juara 2', 'Hadiah Menarik + Sertifikat'),
  ('Billiard 9 Ball', 'Juara 1', 'Hadiah Menarik + Sertifikat'),
  ('Billiard 9 Ball', 'Juara 2', 'Hadiah Menarik + Sertifikat'),
  ('Volleyball', 'Juara 1', 'Hadiah Menarik + Sertifikat'),
  ('Volleyball', 'Juara 2', 'Hadiah Menarik + Sertifikat'),
  ('Chess 1v1', 'Juara 1', 'Hadiah Menarik + Sertifikat'),
  ('Chess 1v1', 'Juara 2', 'Hadiah Menarik + Sertifikat'),
  ('Mobile Legends', 'Juara 1', 'Hadiah Menarik + Sertifikat'),
  ('Mobile Legends', 'Juara 2', 'Hadiah Menarik + Sertifikat'),
  ('Valorant', 'Juara 1', 'Hadiah Menarik + Sertifikat'),
  ('Valorant', 'Juara 2', 'Hadiah Menarik + Sertifikat'),
  ('FIFA 1v1', 'Juara 1', 'Hadiah Menarik + Sertifikat'),
  ('FIFA 1v1', 'Juara 2', 'Hadiah Menarik + Sertifikat'),
  ('PUBG Mobile', 'Juara 1', 'Hadiah Menarik + Sertifikat'),
  ('PUBG Mobile', 'Juara 2', 'Hadiah Menarik + Sertifikat'),
  ('Block Blast', 'Juara 1', 'Hadiah Menarik + Sertifikat'),
  ('Block Blast', 'Juara 2', 'Hadiah Menarik + Sertifikat'),
  ('Modern Dance', 'Juara 1', 'Hadiah Menarik + Sertifikat'),
  ('Modern Dance', 'Juara 2', 'Hadiah Menarik + Sertifikat'),
  ('Modern Dance', 'Juara 3', 'Hadiah Menarik + Sertifikat'),
  ('Ratoh Jaroe', 'Juara 1', 'Hadiah Menarik + Sertifikat'),
  ('Ratoh Jaroe', 'Juara 2', 'Hadiah Menarik + Sertifikat'),
  ('Ratoh Jaroe', 'Juara 3', 'Hadiah Menarik + Sertifikat'),
  ('Band', 'Juara 1', 'Hadiah Menarik + Sertifikat'),
  ('Band', 'Juara 2', 'Hadiah Menarik + Sertifikat'),
  ('Band', 'Juara 3', 'Hadiah Menarik + Sertifikat'),
  ('Cosplay', 'Juara 1', 'Hadiah Menarik + Sertifikat'),
  ('Cosplay', 'Juara 2', 'Hadiah Menarik + Sertifikat'),
  ('Cosplay', 'Juara 3', 'Hadiah Menarik + Sertifikat'),
  ('Cosplay', 'Cosplay Favorit', 'Hadiah Menarik + Sertifikat'),
  ('Art (Sketching)', 'Juara 1', 'Hadiah Menarik + Sertifikat'),
  ('Art (Sketching)', 'Juara 2', 'Hadiah Menarik + Sertifikat'),
  ('Art (Sketching)', 'Juara 3', 'Hadiah Menarik + Sertifikat'),
  ('Art (Sketching)', 'Art Favorit', 'Hadiah Menarik + Sertifikat'),
  ('Cake Decoration', 'Juara 1', 'Hadiah Menarik + Sertifikat'),
  ('Cake Decoration', 'Juara 2', 'Hadiah Menarik + Sertifikat'),
  ('Cake Decoration', 'Juara 3', 'Hadiah Menarik + Sertifikat'),
  ('The Ultimate Automotive Show', 'Juara 1', 'Hadiah Menarik + Sertifikat'),
  ('The Ultimate Automotive Show', 'Juara 2', 'Hadiah Menarik + Sertifikat')
) AS p(competition_name, name, description)
JOIN competitions c ON c.name = p.competition_name
WHERE NOT EXISTS (
  SELECT 1 FROM prizes pr
  WHERE pr.competition_id = c.id AND pr.name = p.name
);

-- Insert Requirements for each competition
INSERT INTO competition_requirements (competition_id, requirement)
SELECT c.id, r.requirement
FROM (VALUES
  ('Basketball', 'Tim terdiri dari 3 pemain inti dan 1 pemain cadangan.'),
  ('Basketball', 'Minimal 3 pemain di lapangan untuk memulai pertandingan.'),
  ('Futsal', 'Setiap tim terdiri dari maksimal 5 pemain di lapangan (1 penjaga gawang + 4 pemain lapangan).'),
  ('Futsal', 'Minimal 3 pemain dibutuhkan agar pertandingan dapat dimulai dan dilanjutkan.'),
  ('Futsal', 'Pemain cadangan maksimal 7 orang.'),
  ('Badminton', 'Kategori pertandingan tunggal (pria/wanita) dan ganda (putra/putri/campuran).'),
  ('Ping Pong 1v1', 'Kategori pertandingan tunggal 1v1 (putra/putri).'),
  ('Billiard 9 Ball', 'Kategori pertandingan billiard putra/putri.'),
  ('Volleyball', 'Setiap tim terdiri dari 10 pemain (6 pemain inti dan 4 pemain cadangan).'),
  ('Volleyball', 'Minimal 4 pemain di lapangan untuk menghindari kalah.'),
  ('Chess 1v1', 'Peserta wajib hadir 15 menit sebelum lomba dimulai.'),
  ('Chess 1v1', 'Peserta wajib mengisi absensi kehadiran.'),
  ('Mobile Legends', 'Setiap tim terdiri dari 5 pemain, dengan 1 cadangan.'),
  ('Mobile Legends', 'Pemain wajib menggunakan device pribadi berupa smartphone (tablet dan iPad tidak diperbolehkan).'),
  ('Mobile Legends', 'Peserta wajib hadir 15 menit sebelum jadwal bertanding.'),
  ('Valorant', 'Peserta wajib menggunakan akun Riot ID pribadi yang telah didaftarkan.'),
  ('Valorant', 'Peserta wajib mengikuti Technical Meeting online sebelum pertandingan pertama.'),
  ('FIFA 1v1', 'Tidak diperkenankan menggunakan akun pribadi; akun permainan akan disediakan oleh panitia.'),
  ('FIFA 1v1', 'Peserta dilarang bermain di bawah pengaruh alkohol atau obat-obatan.'),
  ('PUBG Mobile', 'Peserta wajib standby di lobby 15 menit sebelum pertandingan dimulai.'),
  ('PUBG Mobile', 'Peserta bertanggung jawab untuk memastikan koneksi internet mereka stabil.'),
  ('PUBG Mobile', 'Peserta yang menggunakan kata-kata kasar atau vulgar akan diberi peringatan maksimal 3 kali.'),
  ('Block Blast', 'Peserta harus mematuhi aturan sportivitas dan fairplay.'),
  ('Block Blast', 'Setiap peserta wajib hadir 1 jam sebelum acara dimulai untuk registrasi ulang.'),
  ('Block Blast', 'Panitia akan menyediakan device yang telah disiapkan khusus untuk lomba.'),
  ('Modern Dance', 'Setiap tim terdiri dari minimal 4 dan maksimal 6 peserta.'),
  ('Modern Dance', 'Setiap tim hanya boleh tampil satu kali.'),
  ('Modern Dance', 'Genre lagu bertema “Latin EDM dan Pop”, namun harus bebas SARA & vulgar.'),
  ('Modern Dance', 'Semua tim diwajibkan hadir 60 menit sebelum giliran tampil.'),
  ('Ratoh Jaroe', 'Setiap tim terdiri dari minimal 12 dan maksimal 20 peserta.'),
  ('Ratoh Jaroe', 'Setiap tim hanya boleh tampil satu kali untuk kategori ini.'),
  ('Ratoh Jaroe', 'Satu sekolah boleh mengirim maksimal 1 tim untuk Ratoh Jaroe.'),
  ('Ratoh Jaroe', 'Setiap tim harus memiliki Syekh atau pengiring masing-masing.'),
  ('Band', 'Setiap band terdiri dari minimal 3 dan maksimal 7 personel, termasuk vokalis.'),
  ('Band', 'Setiap band hanya tampil satu kali selama babak kompetisi.'),
  ('Band', 'Genre lagu bertema “Rock Alternatif dan Pop Kreatif”, bebas dari unsur SARA, kekerasan, dan vulgaritas.'),
  ('Band', 'Peserta harus membawakan dua lagu, satu lagu wajib dan satu lagu bebas.'),
  ('Cosplay', 'Peserta dapat berupa perorangan atau tim (maks. 3 orang).'),
  ('Cosplay', 'Setiap peserta hanya diperbolehkan mengikuti 1 penampilan.'),
  ('Cosplay', 'Karakter yang ditampilkan boleh berasal dari Anime/Manga atau Game.'),
  ('Cosplay', 'Karakter harus jelas dan dapat diidentifikasi, tidak boleh OC (original character) tanpa deskripsi jelas.'),
  ('Art (Sketching)', 'Lomba berbentuk menggambar langsung dari model hidup (live model drawing).'),
  ('Art (Sketching)', 'Peserta harus meniru pose model yang telah disiapkan panitia secara realistis dan semirip mungkin.'),
  ('Art (Sketching)', 'Teknik gambar menggunakan pencil.'),
  ('Art (Sketching)', 'Peserta hanya diperbolehkan menggunakan pensil grafit (2H sampai 6B), penghapus, dan blending tool manual.'),
  ('Art (Sketching)', 'Media gambar akan disediakan kertas A3 oleh panitia.'),
  ('Art (Sketching)', 'Peserta membawa alat gambar sendiri (pensil, penghapus, blending tool, dll).'),
  ('Cake Decoration', 'Lomba dilakukan secara on the spot (langsung di tempat).'),
  ('Cake Decoration', 'Dalam satu tim terdiri dari 2 – 3 orang.'),
  ('Cake Decoration', 'Setiap tim akan mendapatkan satu kue polos, bahan hias, dan area kerja masing-masing.'),
  ('Cake Decoration', 'Tema dekorasi akan bernuansa “Fairy Tale”.'),
  ('Cake Decoration', 'Panitia menyediakan meja kerja, kue, alas plastik, dan bahan hias.'),
  ('The Ultimate Automotive Show', 'Peserta diwajibkan menggunakan kendaraan pribadi (baik mobil maupun motor).'),
  ('The Ultimate Automotive Show', 'Pendaftaran dibagi hanya terbuka untuk 5 mobil dan 5 motor.'),
  ('The Ultimate Automotive Show', 'Kompetisi dibagi menjadi dua kategori terpisah: Kategori Mobil dan Kategori Motor.'),
  ('The Ultimate Automotive Show', 'Kendaraan yang digunakan harus dalam kondisi layak jalan.'),
  ('The Ultimate Automotive Show', 'Peserta wajib hadir minimal 30 menit sebelum acara dimulai untuk registrasi ulang dan penempatan kendaraan.')
) AS r(competition_name, requirement)
JOIN competitions c ON c.name = r.competition_name
WHERE NOT EXISTS (
  SELECT 1 FROM competition_requirements cr
  WHERE cr.competition_id = c.id AND cr.requirement = r.requirement
);

-- Insert Rules for each competition
INSERT INTO competition_rules (competition_id, rule)
SELECT c.id, r.rule
FROM (VALUES
  ('Basketball', 'Peraturan Basket 3x3.'),
  ('Basketball', 'Sistem pertandingan akan dilakukan dengan sistem knockout (gugur).'),
  ('Basketball', 'Tim pertama yang mencetak 21 poin atau lebih akan menang, jika terjadi sebelum waktu habis.'),
  ('Basketball', 'Jika skor imbang di akhir waktu reguler, akan ada perpanjangan waktu setelah jeda 1 menit. Tim yang mencetak 2 poin pertama di perpanjangan akan menang.'),
  ('Futsal', 'Peraturan Umum Pertandingan Futsal.'),
  ('Futsal', 'Sistem pertandingan akan dilakukan dengan sistem knockout (gugur).'),
  ('Futsal', 'Pertandingan babak knockout, semifinal dan perebutan juara 3 akan berjalan 2 babak x 15 menit waktu kotor.'),
  ('Futsal', 'Pertandingan final akan berjalan selama 2 babak x 15 menit waktu bersih.'),
  ('Badminton', 'Peraturan Umum Pertandingan Badminton Kategori Tunggal & Ganda.'),
  ('Badminton', 'Sistem pertandingan akan dilakukan dengan sistem knockout (gugur).'),
  ('Badminton', 'Pertandingan menggunakan sistem rally point hingga 21 poin per game.'),
  ('Badminton', 'Pemain/pasangan harus menang dengan selisih 2 poin, namun skor maksimal adalah 30 poin.'),
  ('Ping Pong 1v1', 'Peraturan Umum Pertandingan Ping Pong 1v1.'),
  ('Ping Pong 1v1', 'Sistem pertandingan akan dilakukan dengan sistem knockout (gugur).'),
  ('Ping Pong 1v1', 'Setiap game dimainkan sampai 11 poin, pertandingan akan dimainkan dengan best of three.'),
  ('Ping Pong 1v1', 'Jika skor mencapai 10-10, maka permainan dilanjutkan hingga selisih 2 poin (contoh: 12–10, 13–11, dst).'),
  ('Billiard 9 Ball', 'Peraturan Billiard 9 Ball.'),
  ('Billiard 9 Ball', 'Pertandingan akan dilakukan dengan sistem knockout (gugur).'),
  ('Billiard 9 Ball', 'Bola harus dimasukkan secara berurutan, dimulai dari bola bernomor terkecil yang ada di table.'),
  ('Billiard 9 Ball', 'Pemain yang berhasil memasukkan bola nomor 9 secara sah akan memenangkan permainan (rack).'),
  ('Volleyball', 'Lomba ini diikuti oleh 8 tim yang akan bertanding dalam sistem knockout.'),
  ('Volleyball', 'Menggunakan sistem best of three (3 babak).'),
  ('Volleyball', 'Menggunakan sistem rally point, di mana setiap poin dihitung setelah bola melewati net dan menyentuh lantai lawan.'),
  ('Volleyball', 'Setiap set menggunakan skor 25 poin. Jika kedua tim memiliki poin yang sama (24-24), pertandingan akan dilanjutkan hingga salah satu tim unggul dengan selisih 2 poin.'),
  ('Chess 1v1', 'Format pertandingan: Rapid Chess dengan waktu 10 menit + 5 detik increment per pemain.'),
  ('Chess 1v1', 'Pemenang ditentukan berdasarkan: Checkmate (skak mat), Resignation (lawan menyerah), Timeout (kehabisan waktu), Stalemate atau draw berdasarkan aturan FIDE.'),
  ('Chess 1v1', 'Jika terjadi draw, akan diadakan blitz tie-break dengan waktu 3 menit + 2 detik increment.'),
  ('Chess 1v1', 'Jika masih seri, diadakan Armageddon (pemain putih: 5 menit, pemain hitam: 4 menit, black draw odds).'),
  ('Mobile Legends', 'Semua pertandingan dilakukan secara offline (onsite) di MMG Binus Bekasi.'),
  ('Mobile Legends', 'Pemain tidak diperkenankan melakukan chat all selama pertandingan.'),
  ('Mobile Legends', 'Taunting diperbolehkan selama tidak mengandung SARA, dan Rasisme.'),
  ('Mobile Legends', 'Tim yang tidak lengkap tetap harus melanjutkan pertandingan dengan pemain yang hadir.'),
  ('Valorant', 'Pertandingan dilakukan secara online dengan sistem lobby custom.'),
  ('Valorant', 'Keterlambatan hadir di lobby lebih dari 10 menit setelah waktu yang dijadwalkan akan dianggap WO.'),
  ('Valorant', 'Peserta dilarang keras: Menggunakan cheat, exploit, atau software pihak ketiga; Taunting mengandung unsur SARA, menghina, atau bersifat provokatif; Mengubah roster tim setelah turnamen dimulai.'),
  ('FIFA 1v1', 'Durasi pertandingan: Half time 6 menit (total 12 menit per match).'),
  ('FIFA 1v1', 'Extra time (jika seri): 2 × 3 menit.'),
  ('FIFA 1v1', 'Penalty shootout (jika masih seri setelah extra time): Sistem knock-out langsung.'),
  ('FIFA 1v1', 'Pengaturan difficulty level: Legendary.'),
  ('FIFA 1v1', 'Game Speed: Normal.'),
  ('PUBG Mobile', 'Turnamen menggunakan sistem offline yang berlangsung selama 2 hari.'),
  ('PUBG Mobile', 'Selama 2 hari, peserta akan memainkan total 8 match (4 match per hari).'),
  ('PUBG Mobile', 'Setiap match akan diadakan dengan sistem scoring sheet, yang dihitung berdasarkan total poin dari Place Points dan Kill Points.'),
  ('PUBG Mobile', 'Sistem pertandingan akan menggunakan mode Third Person Perspective (TPP) dan akan dimainkan pada map: Miramar, Sanhok, Vikendi, Erangel.'),
  ('Block Blast', 'Pemenang ditentukan berdasarkan skor tertinggi yang berhasil diperoleh selama 20 sesi permainan.'),
  ('Block Blast', 'Tidak ada sistem poin kumulatif, melainkan purely berdasarkan single highest score.'),
  ('Modern Dance', 'Melebihi durasi lebih dari 1 menit, di kurangi 25 poin.'),
  ('Modern Dance', 'Terdapat kesalahan/lupa gerakan, dikurangi 15 poin.'),
  ('Modern Dance', 'Musik wajib dikirim dalam format MP3 maksimal H-3 sebelum lomba.'),
  ('Modern Dance', 'Lagu yang digunakan tidak boleh mengandung lirik vulgar, SARA, atau ujaran kebencian.'),
  ('Ratoh Jaroe', 'Setiap tim hanya boleh tampil satu kali untuk kategori ini.'),
  ('Ratoh Jaroe', 'Koreografi atau variasi boleh dimodifikasi selama tidak menghilangkan esensi tari Ratoh Jaroe.'),
  ('Ratoh Jaroe', 'Tim wajib menggunakan kostum Ratoh Jaroe sesuai ketentuan untuk perlombaan.'),
  ('Ratoh Jaroe', 'Tidak diperkenankan membawa properti yang berbahaya atau mengandung unsur SARA.'),
  ('Band', 'Peserta dibebaskan untuk aransemen ulang lagu wajib dan lagu bebas.'),
  ('Band', 'Lagu wajib berupa: My Chemical Romance - I don’t love you, Arctic Monkeys - 505, Gun N Roses - Sweet Child O’mine, The rolling stones - doom and gloom, Linkin Park - In the end, Paramore - All i wanted, Oasis - Stop look back in anger, Avenged Sevenfold - After life, juicy luicy - Bukan Orangnya, Dewa 19 - Roman Picisan, Hindia - Cincin, Hivi - Semenjak ada dirimu, Salma Salsabil - Bunga hati, Rony Parulian - Pesona sederhana, Keisya Levronka - Jadi kekasihku saja.'),
  ('Band', 'Maksimal tampil 25 menit, 15 menit untuk check sound & 10 menit untuk tampil.'),
  ('Band', 'Melebihi durasi akan dikenakan pengurangan nilai.'),
  ('Cosplay', 'Karakter harus jelas dan dapat diidentifikasi, tidak boleh OC (original character) tanpa deskripsi jelas.'),
  ('Cosplay', 'Peserta diperbolehkan berakting, berpose dramatis, melakukan adegan singkat, atau berinteraksi imajinatif dengan properti.'),
  ('Cosplay', 'Tidak diperkenankan melempar benda ke penonton atau meninggalkan panggung atau selama penampilan.'),
  ('Cosplay', 'Tidak boleh membuka kostum secara tidak pantas sebagai bagian dari aksi.'),
  ('Art (Sketching)', 'Lomba berbentuk menggambar langsung dari model hidup (live model drawing).'),
  ('Art (Sketching)', 'Peserta harus meniru pose model yang telah disiapkan panitia secara realistis dan semirip mungkin.'),
  ('Art (Sketching)', 'Model akan mempertahankan satu pose tetap selama periode menggambar.'),
  ('Art (Sketching)', 'Teknik gambar menggunakan pencil.'),
  ('Art (Sketching)', 'Peserta hanya diperbolehkan menggunakan pensil grafit (2H sampai 6B), penghapus, dan blending tool manual. Tidak diperbolehkan menggunakan arang, tinta, atau media digital.'),
  ('Cake Decoration', 'Dilarang membawa dekorasi yang sudah jadi (misalnya hiasan bunga siap pakai, topper karakter, dll). Semua elemen harus dibuat di tempat.'),
  ('Cake Decoration', 'Dekorasi harus aman untuk dikonsumsi dan tidak boleh mengandung unsur SARA, kekerasan, atau pornografi.'),
  ('Cake Decoration', 'Peserta tidak boleh meninggalkan area tanpa izin juri saat lomba berlangsung.'),
  ('The Ultimate Automotive Show', 'Kendaraan dengan suara mesin yang mengganggu atau membahayakan peserta lain tidak diperkenankan dinyalakan selama sesi penilaian.'),
  ('The Ultimate Automotive Show', 'Dilarang melakukan aksi burn-out, revving ekstrem, atau demonstrasi performa yang membahayakan di area lomba.'),
  ('The Ultimate Automotive Show', 'Penggunaan part KW / replika atau part yang dibuat sendiri diperbolehkan, namun hanya dinilai berdasarkan keindahan desainnya, bukan kualitas atau fungsionalitas part tersebut.')
) AS r(competition_name, rule)
JOIN competitions c ON c.name = r.competition_name
WHERE NOT EXISTS (
  SELECT 1 FROM competition_rules cr
  WHERE cr.competition_id = c.id AND cr.rule = r.rule
);
