# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Deploy Website
        uses: and-fm/cloudflared-ssh-action@v2.0
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          private_key: ${{secrets.SSH_KEY}}
          
          commands: |
            echo 'Shutting down docker compose..'
            cd BurnCup
            echo "${{secrets.SSH_PASSWORD}}" | sudo -S docker compose down

            cd ..
            
            echo 'Cleaning up old files..'
            echo "${{secrets.SSH_PASSWORD}}" | sudo -S docker image prune -f
            echo "${{secrets.SSH_PASSWORD}}" | sudo -S rm -rf BurnCup
            
            echo 'Cloning the files..'
            echo "${{secrets.SSH_PASSWORD}}" | sudo -S git clone git@github.com:NotchG/BurnCup.git

            cd BurnCup

            echo 'Copying frontend env files..'
            cat <<EOF > .env.local
            ${{ secrets.FRONTEND_ENV }}
            EOF
            cd burncup-fe
            cat <<EOF > .env.local
            ${{ secrets.FRONTEND_ENV }}
            EOF
            
            cd ../
            
            echo 'Starting docker engine'
            
            echo "${{secrets.SSH_PASSWORD}}" | sudo -S docker compose up -d --build --force-recreate
            
            echo 'Engine started and website deployed'
            exit
